CREATE TABLE test_table
(
    id                      INT NOT NULL AUTO_INCREMENT,
    varchar_column          VARCHAR(100),
    char_column             CHAR(100),
    text_column             TEXT,
    longtext_column         LONGTEXT,
    float_column            FLOAT,
    double_column DOUBLE,
    decimal_column          DECIMAL(10, 2),
    bit_column              BIT(1),
    date_column             DATE,
    datetime_column         DATETIME,
    timestamp_column        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    time_column             TIME,
    year_column YEAR,
    binary_column           BINARY(100),
    varbinary_column        VARBINARY(100),
    blob_column             BLOB,
    tinyblob_column         TINYBLOB,
    mediumblob_column       MEDIUMBLOB,
    longblob_column         LONGBLOB,
    enum_column             ENUM('a', 'b', 'c'),
    set_column SET('a', 'b', 'c'),
    json_column             JSON,
    single_index_column     INT NOT NULL,
    composite_index_column1 INT NOT NULL,
    composite_index_column2 INT NOT NULL,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX                   single_index (single_index_column),
    INDEX                   composite_index (composite_index_column1, composite_index_column2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;